title:              My Collection of 
email:              timtimkwan@gmail.com
description:        A Blog that collects my trace
author:             Timothy Kwan(Chun Yin Kwan)
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://unbeknownst6k9.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    Unbeknownst6k9
facebook_username:  StartBootstrap
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

theme: jekyll-theme-slate